### ISSUE TITLE
problem with cdo installation

### ISSUE THREAD

**Issue by maaba5** [markpayneatwork/ClimateOperators#2]
Hi, after cdo installation using(devtools::install_github("markpayneatwork/ClimateOperators"). when I checked the version of cdo, I received this error:

cdo("--version")
Error in system2("cdo", cmd.args, stdout = TRUE) : '"cdo"' not found
[1] "Error in system2(\"cdo\", cmd.args, stdout = TRUE) : '\"cdo\"' not found\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in system2("cdo", cmd.args, stdout = TRUE): '"cdo"' not found>
attr(,"cdo.command")
[1] "cdo --version"

any help?

thank yoyu

**Comment by markpayneatwork** [comment]
Hi,

There are a couple of potential explanations
* You don't have CDO installed. The CDO executables are not included in the package, and need to be installed separately. See here for more details on how to do that. https://code.mpimet.mpg.de/projects/cdo/wiki 
* CDO is installed, but it's not available in your path. Are you able to run cdo from a terminal e.g. using `cdo -h`. 

Which platform are you running on?

Thanks,

Mark

**Comment by maaba5** [comment]
thank you I solved this problem. I have two more question: 
1- can we convert grib file to netcdf with this R package?
2-can we remap grid file using cdo remapbil ?

thank you

**Comment by markpayneatwork** [comment]
Hi,

The package is ajust a wrapper to the CDO set of tools, so whatever CDO can do, can be setup using this package. CDO supports grib files and remapping, so the answer should be yes to both questions. See  the CDO documentation here:

https://code.mpimet.mpg.de/projects/cdo/

Best wishes,

Mark

**Comment by maaba5** [comment]
Hi Mark thank you for you answer, I didn't understand how to use this line:(cdo -f nc copy file.grib2 file.nc) in R using climateOperator package?
Any help?
thank you

**Comment by markpayneatwork** [comment]
This would generate the command that you list, and run it:
`cdo("-f nc copy file.grib2 file.nc")`
